"""Command-line entry point for Model_B behavioral sequence analysis.

The CLI is intentionally thin: it loads a state timeline, optionally smooths
short transients, materializes runs and active sequences, and then augments the
analysis with nominal-comparison artefacts when a reference timeline is
available. This keeps orchestration readable while leaving sequence logic in the
core analyzer class.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Callable

import pandas as pd
from pandas import DatetimeTZDtype

from .sequences import BehavioralSequenceAnalyzer
from .utils import setup_i18n


def parse_arguments(translator: Callable[[str], str]) -> argparse.Namespace:
    """Build the CLI parser for behavioral sequence analysis.

    Args:
        translator: Translation function used for localized help strings.

    Returns:
        Parsed command-line arguments controlling state loading, smoothing,
        nominal comparison, and export format.

    Notes:
        The parser keeps the command surface deliberately small because the
        repository also exposes higher-level batch utilities for long-running
        month-wise orchestration.
    """
    _ = translator
    parser = argparse.ArgumentParser(
        description=_("Behavioral sequence analysis for industrial state timelines")
    )
    parser.add_argument("--input", required=True, help=_("Path to the state timeline file generated by Model_A or digital labeling."))
    parser.add_argument("--nominal-input", help=_("Optional nominal reference timeline used for anomaly comparison."))
    parser.add_argument("--output-dir", required=True, help=_("Directory where Model_B reports will be written."))
    parser.add_argument("--lang", default="en", choices=["es", "en"], help=_("Interface language."))
    parser.add_argument("--state-column", default="Predicted_State", help=_("State column to analyze."))
    parser.add_argument("--smooth-short-runs", action="store_true", help=_("Apply smoothing to transient short runs before sequence extraction."))
    parser.add_argument("--min-duration-seconds", type=float, default=1.0, help=_("Maximum duration treated as a transient run."))
    parser.add_argument("--min-samples", type=int, default=1, help=_("Maximum sample count treated as a transient run."))
    parser.add_argument("--anomaly-threshold", type=float, default=1.0, help=_("Threshold applied to the anomaly score when nominal comparison is enabled."))
    parser.add_argument("--output-format", "--output_format", dest="output_format", choices=["xlsx", "csv"], default="xlsx", help=_("Report export format."))
    return parser.parse_args()


def main() -> None:
    """Run the behavioral-sequence workflow and persist its artefacts.

    Returns:
        ``None``. Results are written to the output directory selected by the
        user.

    Notes:
        When ``--nominal-input`` is provided, the command emits a richer set of
        outputs including anomaly-oriented comparison tables, longitudinal drift
        metrics, recovery metrics, and incident-family signature summaries.
    """
    lang = _detect_language(sys.argv)
    translator = setup_i18n(lang)
    args = parse_arguments(translator)

    analyzer = BehavioralSequenceAnalyzer(state_column=args.state_column)
    timeline = analyzer.load_state_timeline(args.input)
    if args.smooth_short_runs:
        timeline = analyzer.smooth_short_runs(
            timeline,
            min_duration_seconds=args.min_duration_seconds,
            min_samples=args.min_samples,
        )

    runs = analyzer.extract_runs(timeline)
    sequences = analyzer.extract_active_sequences(timeline)
    words = analyzer.summarize_sequence_words(sequences)
    comparisons = pd.DataFrame()
    longitudinal_metrics = pd.DataFrame()
    recovery_metrics = pd.DataFrame()
    family_signatures = pd.DataFrame()

    if args.nominal_input:
        nominal_timeline = analyzer.load_state_timeline(args.nominal_input)
        if args.smooth_short_runs:
            nominal_timeline = analyzer.smooth_short_runs(
                nominal_timeline,
                min_duration_seconds=args.min_duration_seconds,
                min_samples=args.min_samples,
            )
        nominal_sequences = analyzer.extract_active_sequences(nominal_timeline)
        nominal_reference = analyzer.build_nominal_reference(nominal_sequences)
        comparisons = analyzer.compare_to_nominal(
            sequences,
            nominal_reference,
            anomaly_threshold=args.anomaly_threshold,
        )
        longitudinal_metrics = analyzer.compute_longitudinal_metrics(
            sequences,
            nominal_reference,
            anomaly_threshold=args.anomaly_threshold,
        )
        recovery_metrics = analyzer.compute_recovery_metrics(
            sequences,
            nominal_reference,
            anomaly_threshold=args.anomaly_threshold,
        )
        family_signatures = analyzer.summarize_family_signatures(longitudinal_metrics)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    runs_frame = pd.DataFrame([run.__dict__ for run in runs])
    sequences_frame = pd.DataFrame(
        [
            {
                "start_time": sequence.start_time,
                "end_time": sequence.end_time,
                "states": str(sequence.states),
                "total_duration_seconds": sequence.total_duration_seconds,
                "run_count": sequence.run_count,
            }
            for sequence in sequences
        ]
    )

    suffix = args.output_format
    runs_path = output_dir / f"state_runs.{suffix}"
    sequences_path = output_dir / f"active_sequences.{suffix}"
    words_path = output_dir / f"sequence_words.{suffix}"
    comparison_path = output_dir / f"sequence_comparison.{suffix}"
    longitudinal_metrics_path = output_dir / f"sequence_longitudinal_metrics.{suffix}"
    recovery_metrics_path = output_dir / f"recovery_metrics.{suffix}"
    family_signature_path = output_dir / f"incident_episode_metrics.{suffix}"

    _write_report(_prepare_excel_frame(runs_frame), runs_path)
    _write_report(_prepare_excel_frame(sequences_frame), sequences_path)
    _write_report(words, words_path)
    if not comparisons.empty:
        _write_report(comparisons, comparison_path)
        _write_report(longitudinal_metrics, longitudinal_metrics_path)
        _write_report(recovery_metrics, recovery_metrics_path)
        _write_report(family_signatures, family_signature_path)

    print(translator("State-run report saved to: {}").format(runs_path))
    print(translator("Active-sequence report saved to: {}").format(sequences_path))
    print(translator("Sequence-word summary saved to: {}").format(words_path))
    if not comparisons.empty:
        print(translator("Sequence-comparison report saved to: {}").format(comparison_path))
        print(translator("Longitudinal sequence metrics saved to: {}").format(longitudinal_metrics_path))
        print(translator("Recovery metrics saved to: {}").format(recovery_metrics_path))
        print(translator("Incident-family signature report saved to: {}").format(family_signature_path))


def _write_report(frame: pd.DataFrame, path: Path) -> None:
    """Write one output report in CSV or Excel format.

    Args:
        frame: Report dataframe to persist.
        path: Output file path whose suffix selects the writer backend.

    Returns:
        ``None``. The dataframe is written to disk.
    """
    if path.suffix.lower() == ".csv":
        frame.to_csv(path, index=False)
        return
    frame.to_excel(path, index=False)


def _detect_language(argv: list[str]) -> str:
    """Infer the requested CLI language from raw command-line arguments.

    Args:
        argv: Raw command-line argument vector.

    Returns:
        Requested language code, defaulting to English when absent or invalid.
    """
    if "--lang" in argv:
        try:
            return argv[argv.index("--lang") + 1]
        except (IndexError, ValueError):
            return "en"
    return "en"


def _prepare_excel_frame(frame: pd.DataFrame) -> pd.DataFrame:
    """Convert timezone-aware columns into Excel-friendly string values.

    Args:
        frame: Dataframe about to be exported.

    Returns:
        A copy of the input dataframe with timezone-aware timestamps rendered as
        strings when necessary.

    Notes:
        Excel output is kept for backward compatibility with the original
        repository workflow, but timezone-aware timestamps must be stringified
        because native Excel datetime serialization does not preserve them.
    """
    prepared = frame.copy()
    for column in prepared.columns:
        if isinstance(prepared[column].dtype, DatetimeTZDtype):
            prepared[column] = prepared[column].dt.strftime("%Y-%m-%d %H:%M:%S%z")
    return prepared


if __name__ == "__main__":
    main()
